# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'drop_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

from db import Connection_handler


class Drop_DB_Dialog(object):
    def setupUi(self, Dialog):
        """Creates the ui. Mostly autogenerated"""
        Dialog.setObjectName("Dialog")
        Dialog.resize(320, 110)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 70, 301, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.lbl_text = QtWidgets.QLabel(Dialog)
        self.lbl_text.setGeometry(QtCore.QRect(10, 10, 301, 51))
        self.lbl_text.setScaledContents(False)
        self.lbl_text.setWordWrap(True)
        self.lbl_text.setObjectName("lbl_text")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        """Autogenerated function to retranslate the ui"""
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lbl_text.setText(
            _translate("Dialog", "Do you really want to drop the database? All data will be lost forever!"))

    def init(self, Dialog):
        """Init the ui"""
        self.dialog = Dialog
        self.setupUi(Dialog)
        self.buttonBox.accepted.connect(self.drop_db)

    def drop_db(self):
        """Trys to drop the database"""
        # dropped = Connection_handler.drop_database()
        dropped = False
        if not dropped:
            print(1)
            error_message = "There was an error while dropping the Database! Please be sure you stopped the scan and try again"
            self.show_error(error_message)

    def show_error(self, e):
        """TODO"""
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Critical)
        msg.setText("Error")
        msg.setInformativeText(e)
        msg.setWindowTitle("Error")
        msg.show()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Drop_DB_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
